# Generated by Django 4.2.2 on 2023-06-15 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_user_project_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('sport', 'Sport'), ('history', 'History'), ('sciences', 'Sciences'), ('geography', 'Geography'), ('music', 'Music'), ('cinema', 'Cinema'), ('fun facts', 'Funfacts')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=300)),
                ('is_correct', models.BooleanField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.question')),
            ],
        ),
    ]
